import { describe, expect, it, vi } from "vitest";

import {
  buildLiveLogMonitorDeckModelInput,
  buildLiveLogMonitorOperatorActionsInput,
  buildLiveLogMonitorPanelRenderStateInput,
  buildLiveLogMonitorSessionActionsInput,
} from "../../src/features/analyzer/components/liveLogMonitorPanelDeckRuntimeBridge";

function createInput() {
  return {
    t: { inspect: {} },
    repository: { id: "repo-1" },
    monitor: {
      playbackProgress: 12,
      playbackEventCount: 20,
      playbackEventIndex: 3,
      isPlaybackPaused: false,
      session: { repoTitle: "Repo", repoId: "repo-1" },
      metrics: { totalAnomalies: 0 },
      pausePlayback: vi.fn(),
      resumePlayback: vi.fn(),
      seekPlaybackProgress: vi.fn(),
      stepPlaybackWindow: vi.fn(),
    },
    liveEnabled: true,
    replayActive: false,
    playbackPercent: 24,
    playbackWindowLabel: "5/20",
    availableTracks: [],
    availablePlaylists: [],
    availableBaseAssets: [],
    availableCompositions: [],
    surfaceState: {
      adapterKind: "file",
      pendingAddTrackId: null,
      pendingLoadPlaylistId: null,
      beatClockRef: { current: null },
      beatLooperRef: { current: null },
      bounceCuesRef: { current: [] },
      beatClockBpm: 126,
      setBeatClockBpm: vi.fn(),
      bounceWindowCount: 0,
      beatLooperActive: false,
      setBeatLooperActive: vi.fn(),
      backgroundTransitionPlan: null,
      setBackgroundPlayheadSecond: vi.fn(),
      backgroundPlayheadSecond: 18,
      recentWarnings: [],
      setRecentWarnings: vi.fn(),
      error: null,
      setError: vi.fn(),
      isStarting: false,
      setIsStarting: vi.fn(),
      knownComponents: [],
      componentOverrides: {},
      setComponentOverrides: vi.fn(),
      sceneBaseAssetId: "asset-1",
      setSceneBaseAssetId: vi.fn(),
      sceneCompositionId: "composition-1",
      setSceneCompositionId: vi.fn(),
      audioStatus: "ready",
      sampleStatus: "ready",
      lastUpdate: null,
      emittedCueCount: 0,
      emittedVoiceCount: 0,
      recentCues: [],
      recentVoices: [],
      recentMarkers: [],
      recentExplanations: [],
      selectedExplanationId: null,
      setSelectedExplanationId: vi.fn(),
      activeTailWindowId: null,
      syncTailRows: [],
      syncTailListRef: { current: null },
      previousAudibleVolumeRef: { current: 1 },
      selectedStyleProfileId: "style-1",
      setSelectedStyleProfileId: vi.fn(),
      selectedMutationProfileId: "mutation-1",
      setSelectedMutationProfileId: vi.fn(),
      forcedLiveMutationState: "auto",
      setForcedLiveMutationState: vi.fn(),
      masterVolume: 0.7,
      setMasterVolume: vi.fn(),
      audioContextRef: { current: null },
      backgroundGainRef: { current: null },
      backgroundDryGainRef: { current: null },
      backgroundDriveWetGainRef: { current: null },
      backgroundDriveNodeRef: { current: null },
      filterNodeRef: { current: null },
      masterGainRef: { current: null },
      analyserRef: { current: null },
      basePlaylist: [],
      setBasePlaylist: vi.fn(),
      setPendingAddTrackId: vi.fn(),
      setPendingLoadPlaylistId: vi.fn(),
      setAdapterKind: vi.fn(),
      isAnomalyFlash: false,
    },
    selectedStyleProfile: { id: "style-1" },
    selectedMutationProfile: { id: "mutation-1" },
    availableBaseTrackOptions: [],
    backgroundNowPlayingTrack: null,
    backgroundTransitionNextTrack: null,
    traceWaveformTrack: null,
    traceWaveformExplanations: [],
    selectedTraceExplanation: null,
    traceWaveformCues: [],
    currentReplayExplanation: null,
    referenceAnchorBpm: 126,
    scene: { preset: { useBeatGrid: true, rhythmDivision: 0.25 }, sampleSourceCount: 0 },
    baseTrackCount: 0,
    hasBaseListeningBed: false,
    activeAdapterLabel: "FILE_TAIL",
    adapterDescription: "File tail",
    adapterTarget: "/logs/service.log",
    cueEnginePreviewLabel: "Preview",
    liveMutationStateLabel: "Calm",
    replaySessionId: "session-1",
    replayFeedbackRecommendation: null,
    sortedSessionBookmarks: [],
    activeReplayBookmark: null,
    bookmarkLabelDraft: "",
    setBookmarkLabelDraft: vi.fn(),
    bookmarkNoteDraft: "",
    setBookmarkNoteDraft: vi.fn(),
    bookmarkTagDraft: null,
    setBookmarkTagDraft: vi.fn(),
    bookmarkStyleProfileIdDraft: null,
    setBookmarkStyleProfileIdDraft: vi.fn(),
    bookmarkMutationProfileIdDraft: null,
    setBookmarkMutationProfileIdDraft: vi.fn(),
    bookmarkBusy: false,
    bookmarkError: null,
    captureCurrentScene: vi.fn(),
    saveReplayBookmark: vi.fn(),
    deleteReplayBookmark: vi.fn(),
    playPanelTestTone: vi.fn(),
    ensureAudioReady: vi.fn(),
    ensureBackgroundAudio: vi.fn(),
    stopBackgroundDeck: vi.fn(),
    activeBlobAudioElements: new Set(),
    handleSequencerStepFire: vi.fn(),
    applyStartReset: vi.fn(),
    applyStopReset: vi.fn(),
  } as never;
}

describe("liveLogMonitorPanelDeckRuntimeBridge", () => {
  it("builds session/operator/deck/render inputs from the deck runtime contract", () => {
    const input = createInput();
    const operatorActions = {
      handleApplyBookmarkSuggestion: vi.fn(),
      handleApplyReplayFeedbackRecommendation: vi.fn(),
      handleJumpToBookmark: vi.fn(),
      handleSelectTraceExplanation: vi.fn(),
      handleSetMasterVolume: vi.fn(),
      handleToggleMute: vi.fn(),
    };
    const sessionActions = {
      handleStart: vi.fn(),
      handleStop: vi.fn(),
      handleBounce: vi.fn(),
    };
    const liveDeckProps = {
      basePlaylistTrackOptions: [],
      savedPlaylistOptions: [],
      basePlaylistEditorItems: [],
      ctaMetaLabel: "Ready",
      deckStatusLabel: "Stable",
      audioBadgeTone: "info",
      audioBadgeLabel: "Armed",
      bounceAction: { disabled: false },
      liveDeckProps: { title: "deck" },
    } as never;

    expect(buildLiveLogMonitorSessionActionsInput(input)).toMatchObject({
      repository: input.repository,
      adapterKind: "file",
      referenceAnchorBpm: 126,
    });

    expect(buildLiveLogMonitorOperatorActionsInput(input)).toMatchObject({
      repositoryId: "repo-1",
      selectedStyleProfileId: "style-1",
    });

    expect(buildLiveLogMonitorDeckModelInput(input, operatorActions)).toMatchObject({
      playbackPercent: 24,
      adapterTarget: "/logs/service.log",
      onSelectExplanation: operatorActions.handleSelectTraceExplanation,
    });

    expect(
      buildLiveLogMonitorPanelRenderStateInput(input, liveDeckProps, sessionActions),
    ).toMatchObject({
      activeAdapterLabel: "FILE_TAIL",
      deckStatusLabel: "Stable",
      onStop: expect.any(Function),
    });
  });
});
