name = "maia"
type = "javascript"
pages_build_output_dir = "dist"
compatibility_date = "2024-12-16"

[build]
command = "npm install && npm run build"
cwd = "."
watch_paths = ["src/**/*.{jsx,js,ts,tsx}", "public/**/*"]
