import type { GenreProfile } from "./liveSonificationSceneProfileData";

export const HOUSE_GENRE_PROFILES: Record<string, GenreProfile> = {
  house: {
    label: "House",
    infoWaveform: "triangle",
    warnWaveform: "triangle",
    errorWaveform: "sawtooth",
    anomalyWaveform: "sawtooth",
    noteMultiplier: 1.0,
    durationScale: 0.9,
    gainScale: 1.08,
    infoLabel: "Steady groove",
    warnLabel: "Filter lift",
    errorLabel: "Peak surge",
    anomalyLabel: "Off-beat accent",
    descriptor: "warm 4x4 instrumental groove",
  },
  "melodic-house": {
    label: "Melodic House",
    infoWaveform: "sine",
    warnWaveform: "triangle",
    errorWaveform: "sawtooth",
    anomalyWaveform: "sawtooth",
    noteMultiplier: 1.04,
    durationScale: 1.06,
    gainScale: 0.96,
    infoLabel: "Melodic pulse",
    warnLabel: "Harmonic rise",
    errorLabel: "Melodic peak",
    anomalyLabel: "Detuned accent",
    descriptor: "melodic instrumental flow",
  },
  "progressive-house": {
    label: "Progressive House",
    infoWaveform: "sine",
    warnWaveform: "triangle",
    errorWaveform: "sawtooth",
    anomalyWaveform: "sawtooth",
    noteMultiplier: 1.02,
    durationScale: 1.18,
    gainScale: 0.98,
    infoLabel: "Baseline phrase",
    warnLabel: "Build phrase",
    errorLabel: "Break surge",
    anomalyLabel: "Lift accent",
    descriptor: "long-build instrumental arrangement",
  },
  "tropical-house": {
    label: "Tropical House",
    infoWaveform: "sine",
    warnWaveform: "triangle",
    errorWaveform: "triangle",
    anomalyWaveform: "sawtooth",
    noteMultiplier: 1.12,
    durationScale: 0.85,
    gainScale: 1.25,
    infoLabel: "Pluck pulse",
    warnLabel: "Tropical rise",
    errorLabel: "Sunset surge",
    anomalyLabel: "Steel drum accent",
    descriptor: "chill instrumental tropical house",
  },
};
