import type { CategoryProfile } from "./liveSonificationSceneProfileData";

export const CATEGORY_PROFILES: Record<string, CategoryProfile> = {
  collection: {
    baseWaveform: "triangle",
    warnWaveform: "triangle",
    errorWaveform: "sawtooth",
    anomalyWaveform: "sawtooth",
    noteMultiplier: 1,
    durationScale: 1,
    gainScale: 1,
    panBias: 0,
    descriptor: "balanced reusable collection",
  },
  "drum-kit": {
    baseWaveform: "square",
    warnWaveform: "triangle",
    errorWaveform: "square",
    anomalyWaveform: "sawtooth",
    noteMultiplier: 0.76,
    durationScale: 0.78,
    gainScale: 1.12,
    panBias: 0,
    descriptor: "tight transient kit",
  },
  "bass-motif": {
    baseWaveform: "sawtooth",
    warnWaveform: "triangle",
    errorWaveform: "sawtooth",
    anomalyWaveform: "square",
    noteMultiplier: 0.64,
    durationScale: 0.92,
    gainScale: 1.08,
    panBias: -0.04,
    descriptor: "low-end anchor",
  },
  "pad-texture": {
    baseWaveform: "sine",
    warnWaveform: "triangle",
    errorWaveform: "triangle",
    anomalyWaveform: "sawtooth",
    noteMultiplier: 1.08,
    durationScale: 1.34,
    gainScale: 0.88,
    panBias: -0.12,
    descriptor: "atmospheric bed",
  },
  "fx-palette": {
    baseWaveform: "triangle",
    warnWaveform: "sawtooth",
    errorWaveform: "sawtooth",
    anomalyWaveform: "sawtooth",
    noteMultiplier: 1.24,
    durationScale: 0.72,
    gainScale: 1.06,
    panBias: 0.18,
    descriptor: "transition accent pack",
  },
  "vocal-hook": {
    baseWaveform: "square",
    warnWaveform: "triangle",
    errorWaveform: "square",
    anomalyWaveform: "sawtooth",
    noteMultiplier: 1.28,
    durationScale: 1.08,
    gainScale: 0.96,
    panBias: 0.08,
    descriptor: "hook-forward topline layer",
  },
  "code-pattern": {
    baseWaveform: "triangle",
    warnWaveform: "triangle",
    errorWaveform: "square",
    anomalyWaveform: "sawtooth",
    noteMultiplier: 0.94,
    durationScale: 0.94,
    gainScale: 1,
    panBias: 0,
    descriptor: "structural pattern motif",
  },
};
