import type { UseLiveLogMonitorPanelRuntimeInput } from "./useLiveLogMonitorPanelRuntime";
import type { useLiveLogMonitorPanelRuntimeState } from "./useLiveLogMonitorPanelRuntimeState";
import type { LiveLogStreamUpdate } from "../../../types/library";

type LiveLogMonitorPanelRuntimeState = ReturnType<typeof useLiveLogMonitorPanelRuntimeState>;

export function buildLiveLogMonitorOrchestratorInput(
  input: UseLiveLogMonitorPanelRuntimeInput,
  runtimeState: LiveLogMonitorPanelRuntimeState,
) {
  return {
    repositoryId: input.repository.id,
    sessionRepoId: input.monitor.session?.repoId ?? null,
    audioContextRef: input.surfaceState.audioContextRef,
    backgroundDeckRef: input.surfaceState.backgroundDeckRef,
    beatClockRef: input.surfaceState.beatClockRef,
    panelAudioProbePlayedRef: input.surfaceState.panelAudioProbePlayedRef,
    scene: runtimeState.scene,
    availableTracks: input.availableTracks,
    componentOverrides: input.surfaceState.componentOverrides,
    replayActive: input.replayActive,
    knownComponentsRef: input.surfaceState.knownComponentsRef,
    setLastUpdate: input.surfaceState.setLastUpdate,
    setRecentWarnings: input.surfaceState.setRecentWarnings,
    setError: input.surfaceState.setError,
    setSyncTailRows: input.surfaceState.setSyncTailRows,
    setActiveTailWindowId: input.surfaceState.setActiveTailWindowId,
    setIsAnomalyFlash: input.surfaceState.setIsAnomalyFlash,
    setEmittedCueCount: input.surfaceState.setEmittedCueCount,
    setRecentCues: input.surfaceState.setRecentCues,
    setRecentMarkers: input.surfaceState.setRecentMarkers,
    setRecentExplanations: input.surfaceState.setRecentExplanations,
    setBackgroundPlayheadSecond: input.surfaceState.setBackgroundPlayheadSecond,
    setSelectedExplanationId: input.surfaceState.setSelectedExplanationId,
    setRecentVoices: input.surfaceState.setRecentVoices,
    setKnownComponents: input.surfaceState.setKnownComponents,
    setBeatClockBpm: input.surfaceState.setBeatClockBpm,
    monitor: {
      isPlayback: input.monitor.isPlayback,
    },
    ensureAudioReady: runtimeState.ensureAudioReady,
    playWithCurrentEngine: runtimeState.playbackRuntime.playWithCurrentEngine,
    applyLogModulation: runtimeState.applyLogModulation,
    playPanelTestTone: runtimeState.playPanelTestTone,
    logger: {
      info: () => undefined,
      debug: () => undefined,
      trace: () => undefined,
    },
  };
}

export function buildLiveLogMonitorLifecycleInput(
  input: UseLiveLogMonitorPanelRuntimeInput,
  runtimeState: LiveLogMonitorPanelRuntimeState,
  onStreamUpdate: (update: LiveLogStreamUpdate) => void,
) {
  return {
    repository: input.repository,
    availableBaseAssets: input.availableBaseAssets,
    availableCompositions: input.availableCompositions,
    availableTracks: input.availableTracks,
    preferredBaseAssetId: input.preferredBaseAssetId,
    preferredCompositionId: input.preferredCompositionId,
    basePlaylist: input.surfaceState.basePlaylist,
    guideTrackPath: input.monitor.guideTrackPath,
    replayActive: input.replayActive,
    onStreamUpdate,
    subscribe: input.monitor.subscribe,
    activeBlobAudioElements: runtimeState.activeBlobAudioElements,
    audioContextRef: input.surfaceState.audioContextRef,
    usingSharedAudioContextRef: input.surfaceState.usingSharedAudioContextRef,
    setSceneBaseAssetId: input.surfaceState.setSceneBaseAssetId,
    setSceneCompositionId: input.surfaceState.setSceneCompositionId,
    setBasePlaylist: input.surfaceState.setBasePlaylist,
    applyRepositoryReset: runtimeState.resetActions.applyRepositoryReset,
  };
}

export function buildLiveLogMonitorDeckRuntimeInput(
  input: UseLiveLogMonitorPanelRuntimeInput,
  runtimeState: LiveLogMonitorPanelRuntimeState,
) {
  return {
    t: input.t,
    repository: input.repository,
    monitor: input.monitor,
    liveEnabled: input.liveEnabled,
    replayActive: input.replayActive,
    playbackPercent: input.playbackPercent,
    playbackWindowLabel: input.playbackWindowLabel,
    availableTracks: input.availableTracks,
    availablePlaylists: input.availablePlaylists,
    availableBaseAssets: input.availableBaseAssets,
    availableCompositions: input.availableCompositions,
    surfaceState: input.surfaceState,
    selectedStyleProfile: runtimeState.selectedStyleProfile,
    selectedMutationProfile: runtimeState.selectedMutationProfile,
    availableBaseTrackOptions: runtimeState.availableBaseTrackOptions,
    backgroundNowPlayingTrack: runtimeState.backgroundNowPlayingTrack,
    backgroundTransitionNextTrack: runtimeState.backgroundTransitionNextTrack,
    traceWaveformTrack: runtimeState.traceWaveformTrack,
    traceWaveformExplanations: runtimeState.traceWaveformExplanations,
    selectedTraceExplanation: runtimeState.selectedTraceExplanation,
    traceWaveformCues: runtimeState.traceWaveformCues,
    currentReplayExplanation: runtimeState.currentReplayExplanation,
    referenceAnchorBpm: runtimeState.referenceAnchor?.bpm ?? null,
    scene: runtimeState.scene,
    baseTrackCount: runtimeState.baseTrackCount,
    hasBaseListeningBed: runtimeState.hasBaseListeningBed,
    activeAdapterLabel: runtimeState.activeAdapterLabel,
    adapterDescription: runtimeState.adapterDescription,
    adapterTarget: runtimeState.adapterTarget,
    cueEnginePreviewLabel: runtimeState.cueEnginePreviewLabel,
    liveMutationStateLabel: runtimeState.liveMutationStateLabel,
    replaySessionId: runtimeState.replayState.replaySessionId,
    replayFeedbackRecommendation: runtimeState.replayState.replayFeedbackRecommendation,
    sortedSessionBookmarks: runtimeState.replayState.sortedSessionBookmarks,
    activeReplayBookmark: runtimeState.replayState.activeReplayBookmark,
    bookmarkLabelDraft: runtimeState.replayState.bookmarkLabelDraft,
    setBookmarkLabelDraft: runtimeState.replayState.setBookmarkLabelDraft,
    bookmarkNoteDraft: runtimeState.replayState.bookmarkNoteDraft,
    setBookmarkNoteDraft: runtimeState.replayState.setBookmarkNoteDraft,
    bookmarkTagDraft: runtimeState.replayState.bookmarkTagDraft,
    setBookmarkTagDraft: runtimeState.replayState.setBookmarkTagDraft,
    bookmarkStyleProfileIdDraft: runtimeState.replayState.bookmarkStyleProfileIdDraft,
    setBookmarkStyleProfileIdDraft: runtimeState.replayState.setBookmarkStyleProfileIdDraft,
    bookmarkMutationProfileIdDraft: runtimeState.replayState.bookmarkMutationProfileIdDraft,
    setBookmarkMutationProfileIdDraft: runtimeState.replayState.setBookmarkMutationProfileIdDraft,
    bookmarkBusy: runtimeState.replayState.bookmarkBusy,
    bookmarkError: runtimeState.replayState.bookmarkError,
    captureCurrentScene: runtimeState.replayState.captureCurrentScene,
    saveReplayBookmark: runtimeState.replayState.saveReplayBookmark,
    deleteReplayBookmark: runtimeState.replayState.deleteReplayBookmark,
    playPanelTestTone: runtimeState.playPanelTestTone,
    ensureAudioReady: runtimeState.ensureAudioReady,
    ensureBackgroundAudio: runtimeState.backgroundDeckControl.ensureBackgroundAudio,
    stopBackgroundDeck: runtimeState.backgroundDeckControl.stopBackgroundDeck,
    activeBlobAudioElements: runtimeState.activeBlobAudioElements,
    handleSequencerStepFire: runtimeState.playbackRuntime.handleSequencerStepFire,
    applyStartReset: runtimeState.resetActions.applyStartReset,
    applyStopReset: runtimeState.resetActions.applyStopReset,
  };
}
