import type { GenreProfile } from "./liveSonificationSceneProfileData";

export const CLUB_GENRE_PROFILES: Record<string, GenreProfile> = {
  edm: {
    label: "EDM",
    infoWaveform: "square",
    warnWaveform: "square",
    errorWaveform: "sawtooth",
    anomalyWaveform: "sawtooth",
    noteMultiplier: 1.05,
    durationScale: 0.72,
    gainScale: 1.18,
    infoLabel: "Synth lead pulse",
    warnLabel: "Stab rise",
    errorLabel: "Drop surge",
    anomalyLabel: "Sidechain accent",
    descriptor: "punchy festival instrumental",
  },
  techno: {
    label: "Techno",
    infoWaveform: "square",
    warnWaveform: "square",
    errorWaveform: "square",
    anomalyWaveform: "sawtooth",
    noteMultiplier: 0.92,
    durationScale: 0.68,
    gainScale: 1.22,
    infoLabel: "Kick pulse",
    warnLabel: "Clap hit",
    errorLabel: "Distortion burst",
    anomalyLabel: "Glitch accent",
    descriptor: "dense percussive instrumental",
  },
  trance: {
    label: "Trance",
    infoWaveform: "sine",
    warnWaveform: "triangle",
    errorWaveform: "sawtooth",
    anomalyWaveform: "sawtooth",
    noteMultiplier: 1.08,
    durationScale: 1.18,
    gainScale: 1.0,
    infoLabel: "Pad sweep",
    warnLabel: "Filter tension",
    errorLabel: "Supersaw burst",
    anomalyLabel: "Arpeggio accent",
    descriptor: "euphoric instrumental sweep",
  },
};
