import {
  buildLiveLogMonitorDeckBookmarkCallbacks,
  buildLiveLogMonitorDeckPlaybackCallbacks,
  type LiveLogMonitorDeckOperatorActions,
} from "./liveLogMonitorPanelDeckCallbacksRuntime";
import type { UseLiveLogMonitorPanelDeckRuntimeInput } from "./useLiveLogMonitorPanelDeckRuntime";

export function buildLiveLogMonitorDeckModelInput(
  input: UseLiveLogMonitorPanelDeckRuntimeInput,
  operatorActions: LiveLogMonitorDeckOperatorActions,
) {
  const surfaceState = input.surfaceState;
  const playbackCallbacks = buildLiveLogMonitorDeckPlaybackCallbacks(input);
  const bookmarkCallbacks = buildLiveLogMonitorDeckBookmarkCallbacks(input, operatorActions);

  return {
    t: input.t,
    repository: input.repository,
    liveEnabled: input.liveEnabled,
    replayActive: input.replayActive,
    playbackPercent: input.playbackPercent,
    playbackWindowLabel: input.playbackWindowLabel,
    playbackProgress: input.monitor.playbackProgress,
    playbackEventCount: input.monitor.playbackEventCount,
    playbackEventIndex: input.monitor.playbackEventIndex,
    isPlaybackPaused: input.monitor.isPlaybackPaused,
    persistedSessionId: input.replaySessionId,
    sessionRepoTitle: input.monitor.session?.repoTitle ?? null,
    sessionRepoId: input.monitor.session?.repoId ?? null,
    session: input.monitor.session,
    metrics: input.monitor.metrics,
    bounceWindowCount: surfaceState.bounceWindowCount,
    beatClockBpm: surfaceState.beatClockBpm,
    beatLooperActive: surfaceState.beatLooperActive,
    backgroundPlayheadSecond: surfaceState.backgroundPlayheadSecond,
    backgroundNowPlayingTrack: input.backgroundNowPlayingTrack,
    backgroundTransitionNextTrack: input.backgroundTransitionNextTrack,
    backgroundTransitionPlan: surfaceState.backgroundTransitionPlan,
    availableTracks: input.availableTracks,
    availablePlaylists: input.availablePlaylists,
    availableBaseAssets: input.availableBaseAssets,
    availableCompositions: input.availableCompositions,
    availableBaseTrackOptions: input.availableBaseTrackOptions,
    basePlaylist: surfaceState.basePlaylist,
    baseTrackCount: input.baseTrackCount,
    hasBaseListeningBed: input.hasBaseListeningBed,
    adapterDescription: input.adapterDescription,
    adapterTarget: input.adapterTarget,
    activeAdapterLabel: input.activeAdapterLabel,
    cueEnginePreviewLabel: input.cueEnginePreviewLabel,
    liveMutationStateLabel: input.liveMutationStateLabel,
    lastUpdate: surfaceState.lastUpdate,
    recentMarkers: surfaceState.recentMarkers,
    recentWarnings: surfaceState.recentWarnings,
    recentCues: surfaceState.recentCues,
    recentVoices: surfaceState.recentVoices,
    recentExplanations: surfaceState.recentExplanations,
    selectedExplanationId: surfaceState.selectedExplanationId,
    selectedTraceExplanation: input.selectedTraceExplanation,
    traceWaveformTrack: input.traceWaveformTrack,
    traceWaveformExplanations: input.traceWaveformExplanations,
    traceWaveformCues: input.traceWaveformCues,
    activeTailWindowId: surfaceState.activeTailWindowId,
    syncTailRows: surfaceState.syncTailRows,
    analyserRef: surfaceState.analyserRef,
    syncTailListRef: surfaceState.syncTailListRef,
    error: surfaceState.error,
    isAnomalyFlash: surfaceState.isAnomalyFlash,
    audioStatus: surfaceState.audioStatus,
    sampleStatus: surfaceState.sampleStatus,
    sampleSourceCount: input.scene.sampleSourceCount,
    emittedCueCount: surfaceState.emittedCueCount,
    emittedVoiceCount: surfaceState.emittedVoiceCount,
    selectedStyleProfile: input.selectedStyleProfile,
    selectedMutationProfile: input.selectedMutationProfile,
    scene: input.scene,
    sceneBaseAssetId: surfaceState.sceneBaseAssetId,
    sceneCompositionId: surfaceState.sceneCompositionId,
    knownComponents: surfaceState.knownComponents,
    componentOverrides: surfaceState.componentOverrides,
    masterVolume: surfaceState.masterVolume,
    replayFeedbackRecommendation: input.replayFeedbackRecommendation,
    activeReplayBookmark: input.activeReplayBookmark,
    sortedSessionBookmarks: input.sortedSessionBookmarks,
    bookmarkLabelDraft: input.bookmarkLabelDraft,
    bookmarkNoteDraft: input.bookmarkNoteDraft,
    bookmarkTagDraft: input.bookmarkTagDraft,
    bookmarkStyleProfileIdDraft: input.bookmarkStyleProfileIdDraft,
    bookmarkMutationProfileIdDraft: input.bookmarkMutationProfileIdDraft,
    bookmarkBusy: input.bookmarkBusy,
    bookmarkError: input.bookmarkError,
    setComponentOverrides: surfaceState.setComponentOverrides,
    setSceneBaseAssetId: surfaceState.setSceneBaseAssetId,
    setSceneCompositionId: surfaceState.setSceneCompositionId,
    onSequencerStepFire: input.handleSequencerStepFire,
    ...playbackCallbacks,
    ...bookmarkCallbacks,
  };
}
