import { renderHook } from "@testing-library/react";
import { describe, expect, it, vi } from "vitest";

import { useAppV0ScreenModel } from "../../src/hooks/useAppV0ScreenModel";

describe("useAppV0ScreenModel", () => {
  it("assembles content actions, section props, and shell model for App-v0", () => {
    const result = renderHook(() =>
      useAppV0ScreenModel({
        userMode: "simple",
        lang: "en",
        skin: "nightfall",
        setupPreferences: {
          defaultCloudLookback: "10m",
          idleHoldMs: 900,
          tailWindowRows: 1200,
        },
        updateSetupPreference: vi.fn(),
        setLang: vi.fn(),
        setSkin: vi.fn(),
        currentSection: "monitor",
        setCurrentSection: vi.fn(),
        isSidebarCollapsed: false,
        toggleSidebarCollapsed: vi.fn(),
        isConsoleExpanded: true,
        toggleConsoleExpanded: vi.fn(),
        openMonitorInspector: vi.fn(),
        fallbackViewModel: {
          message: "Nothing here",
          hint: "Use the sidebar",
        },
        shellViewModel: {
          monitoringStatus: {
            source: "visits-service",
            anomalies: 3,
            uptime: "14s",
            confidence: 87,
          },
          selectedItem: "visits-service",
          floatingWaveformBar: {
            isVisible: true,
            source: "visits-service",
            anomalies: 3,
            uptime: "14s",
          },
        },
        waveformBins: [0.2, 0.4],
        isMonitoring: true,
        reportMonitorLaunchFailure: vi.fn(),
        monitor: {
          session: {
            sessionId: "session-1",
            persistedSessionId: null,
            repoId: "repo-1",
            repoTitle: "visits-service",
            trackId: "track-1",
            trackName: "Deck Track",
            sourcePath: "/logs/visits-service.log",
            adapterKind: "file",
            pollMode: "session",
            startedAt: 1,
          },
          metrics: {
            windowCount: 1,
            processedLines: 12,
            totalAnomalies: 3,
          },
          stopSession: vi.fn(async () => undefined),
          resumeAudio: vi.fn(async () => undefined),
          subscribe: vi.fn(() => vi.fn()),
          audioContext: {
            state: "running",
          } as AudioContext,
        },
        library: {
          tracks: [
            {
              id: "track-1",
              title: "Deck Track",
              sourcePath: "/music/deck-track.wav",
              storagePath: null,
              importedAt: "2026-01-01T00:00:00Z",
              bpm: 126,
              bpmConfidence: 0.9,
              durationSeconds: 320,
              waveformBins: [0.2, 0.4],
              beatGrid: [],
              bpmCurve: [],
              analyzerStatus: "ready",
              repoSuggestedBpm: null,
              repoSuggestedStatus: "idle",
              notes: [],
              fileExtension: "wav",
              analysisMode: "track",
              musicStyleId: "house",
              musicStyleLabel: "House",
              keySignature: null,
              energyLevel: null,
              danceability: null,
              structuralPatterns: [],
              file: {
                sourcePath: "/music/deck-track.wav",
                storagePath: null,
                sourceKind: "file",
                fileExtension: "wav",
                sizeBytes: 10,
                modifiedAt: null,
                checksum: null,
                availabilityState: "available",
                playbackSource: "source_file",
              },
              tags: {
                title: "Deck Track",
                artist: null,
                album: null,
                genre: null,
                year: null,
                comment: null,
                artworkPath: null,
                musicStyleId: "house",
                musicStyleLabel: "House",
              },
              analysis: {
                importedAt: "2026-01-01T00:00:00Z",
                bpm: 126,
                bpmConfidence: 0.9,
                durationSeconds: 320,
                waveformBins: [0.2, 0.4],
                beatGrid: [],
                bpmCurve: [],
                analyzerStatus: "ready",
                analysisMode: "track",
                analyzerVersion: null,
                analyzedAt: null,
                repoSuggestedBpm: null,
                repoSuggestedStatus: "idle",
                notes: [],
                keySignature: null,
                energyLevel: null,
                danceability: null,
                structuralPatterns: [],
              },
              performance: {
                color: null,
                rating: 0,
                playCount: 0,
                lastPlayedAt: null,
                bpmLock: false,
                gridLock: false,
                mainCueSecond: null,
                hotCues: [],
                memoryCues: [],
                savedLoops: [],
              },
            },
          ],
          selectedTrackId: "track-1",
          selectedTrack: null,
          setSelectedTrackId: vi.fn(),
        },
        repositories: {
          repositories: [
            {
              id: "repo-1",
              title: "visits-service",
              sourcePath: "/logs/visits-service.log",
              storagePath: null,
              sourceKind: "file",
              importedAt: "2026-01-01T00:00:00Z",
              suggestedBpm: 126,
              confidence: 0.9,
              summary: "",
              analyzerStatus: "ready",
              buildSystem: "",
              primaryLanguage: "log",
              javaFileCount: 0,
              testFileCount: 0,
              waveformBins: [],
              beatGrid: [],
              bpmCurve: [],
              notes: [],
              tags: [],
              metrics: {},
            },
          ],
          selectedRepositoryId: "repo-1",
          setSelectedRepositoryId: vi.fn(),
          importRepositorySource: vi.fn(async () => ({ id: "repo-1" })),
        },
        baseAssets: {
          baseAssets: [],
          importLibraryBaseAsset: vi.fn(async () => null),
        },
        pastSessions: {
          sessions: [],
        },
        monitorOrchestrator: {
          startLibraryMonitoring: vi.fn(async () => ({ ok: true as const })),
          startSourceMonitoring: vi.fn(async () => ({ ok: true as const })),
          replaySession: vi.fn(async () => undefined),
        },
      }),
    );

    expect(result.result.current.sectionContentInput.currentSection).toBe("monitor");
    expect(result.result.current.sectionContentInput.skin).toBe("nightfall");
    expect(result.result.current.sectionContentInput.isConsoleExpanded).toBe(true);
    expect(result.result.current.screenModel.appShellProps.currentSection).toBe("monitor");
    expect(result.result.current.screenModel.floatingWaveformBarProps).toMatchObject({
      source: "visits-service",
      anomalies: 3,
      uptime: "14s",
    });
    expect(result.result.current.contentActions.onStartMonitoring).toBeTypeOf("function");
  });
});
