import { AppV0SectionRenderer } from "./AppV0SectionRenderer";
import {
  buildAppV0SectionRenderModel,
  type AppV0SectionContentInput,
} from "./appV0SectionContentRuntime";

type AppV0SectionContentProps = AppV0SectionContentInput;

export function AppV0SectionContent({
  currentSection,
  userMode,
  fallbackViewModel,
  setupPreferences,
  lang,
  skin,
  onChangeLanguage,
  onChangeSkin,
  onUpdateSetupPreference,
  monitorSession,
  monitorMetrics,
  pastSessions,
  repositories,
  tracks,
  baseAssets,
  selectedRepositoryId,
  onSelectRepository,
  onImportRepository,
  onImportBaseAsset,
  selectedTrackId,
  onSelectTrack,
  onStartLibraryMonitoring,
  onStopMonitor,
  onResumeAudio,
  audioStatus,
  audioContext,
  monitorTrackName,
  waveformBins,
  onStartMonitoring,
  onReplaySession,
  subscribe,
  isConsoleExpanded,
  onToggleConsole,
}: AppV0SectionContentProps) {
  const renderModel = buildAppV0SectionRenderModel({
    currentSection,
    userMode,
    fallbackViewModel,
    setupPreferences,
    lang,
    skin,
    onChangeLanguage,
    onChangeSkin,
    onUpdateSetupPreference,
    monitorSession,
    monitorMetrics,
    pastSessions,
    repositories,
    tracks,
    baseAssets,
    selectedRepositoryId,
    onSelectRepository,
    onImportRepository,
    onImportBaseAsset,
    selectedTrackId,
    onSelectTrack,
    onStartLibraryMonitoring,
    onStopMonitor,
    onResumeAudio,
    audioStatus,
    audioContext,
    monitorTrackName,
    waveformBins,
    onStartMonitoring,
    onReplaySession,
    subscribe,
    isConsoleExpanded,
    onToggleConsole,
  });

  return <AppV0SectionRenderer renderModel={renderModel} />;
}
