import { useMonitorDeckControls } from "./useMonitorDeckControls";
import { useSimpleMonitorPlaybackState } from "./useSimpleMonitorPlaybackState";
import { useSimpleMonitorDeckPresentationState } from "./useSimpleMonitorDeckPresentationState";
import { useSimpleMonitorDeckLiveController } from "./useSimpleMonitorDeckLiveController";
import {
  buildSimpleMonitorDeckHookState,
  buildMonitorDeckPresentationHookInput,
  buildSimpleMonitorDeckRuntimeState,
} from "./simpleMonitorDeckRuntime";
import type { WaveformAnomalyMarker } from "./monitorDeckViewModel";
import type { UseSimpleMonitorDeckRuntimeInput } from "./simpleMonitorDeckRuntimeTypes";

const SAFE_MONITOR_RUNTIME = false;

export function useSimpleMonitorDeckController({
  skin,
  session,
  isListening,
  isLaunchingMonitor,
  safeTracks,
  trackName,
  audioContext,
  subscribe,
  waveformBins,
  isConsoleExpanded,
  onToggleConsole,
  liveSettings,
  t,
}: UseSimpleMonitorDeckRuntimeInput) {
  const { deckControls, activePreset } = useMonitorDeckControls({ skin });
  const {
    trackWaveProgress,
    setTrackWaveProgress,
    trackElapsedSeconds,
    setTrackElapsedSeconds,
    trackDurationSeconds,
    setTrackDurationSeconds,
    trackWaveProgressRef,
  } = useSimpleMonitorPlaybackState({
    isListening,
  });
  const baseDeckState = buildSimpleMonitorDeckRuntimeState({
    session,
    isListening,
    isLaunchingMonitor,
    tracks: safeTracks,
    trackName,
    trackDurationSeconds,
    activePreset,
    alertShape: deckControls.alertShape,
    liveSuggestedBpm: null,
    t,
  });
  const {
    activeTrack,
    deckDurationSeconds,
    activeBeatGrid,
    streamAdapterLabel,
    isMonitorActive,
    deckPresetLabel,
    deckVisualPreset,
  } = baseDeckState;
  const {
    backgroundAudioRef,
    previewTrackId,
    toggleTrackPreview,
    liveLines,
    logSignalBuffer,
    liveSuggestedBpm,
    waveformAnomalies,
    selectedAnomalyId,
    setSelectedAnomalyId,
    simulateLog,
  } = useSimpleMonitorDeckLiveController({
    audioContext,
    isListening,
    deckControls,
    activeTrack,
    deckDurationSeconds,
    session,
    streamAdapterLabel,
    subscribe,
    trackWaveProgressRef,
    setTrackWaveProgress,
    setTrackElapsedSeconds,
    setTrackDurationSeconds,
    liveSettings,
  });
  const { deckBpm } = buildSimpleMonitorDeckRuntimeState({
    session,
    isListening,
    isLaunchingMonitor,
    tracks: safeTracks,
    trackName,
    trackDurationSeconds,
    activePreset,
    alertShape: deckControls.alertShape,
    liveSuggestedBpm,
    t,
  });
  const {
    terminalLinesRef,
    onTerminalScroll,
    registerLineRef,
    focusAnomaly,
    overviewCanvasRef,
    waveformCanvasRef,
    waveformStageRef,
    handleOverviewPointerDown,
    handleOverviewClick,
    handleOverviewAnomalyClick,
    handleOverviewAnomalyPointerDown,
    handleStagePointerDown,
    handleStageClick,
    anomalyBurstRegions,
    overviewWindowWidthPercent,
    overviewWindowLeftPercent,
    overviewPlayheadLeftPercent,
    overviewAnomalyMarkers,
    selectedDeckMarker,
    selectedBurstRegion,
    deckTimelineMarkers,
    deckBeatMarkers,
  } = useSimpleMonitorDeckPresentationState(
    buildMonitorDeckPresentationHookInput({
      backgroundAudioRef,
      waveformBins,
      waveformAnomalies: waveformAnomalies as WaveformAnomalyMarker[],
      trackWaveProgress,
      setTrackWaveProgress,
      setTrackElapsedSeconds,
      deckDurationSeconds,
      deckBpm,
      activeBeatGrid,
      logSignalBuffer,
      selectedAnomalyId,
      setSelectedAnomalyId,
      liveLines,
      isConsoleExpanded,
      onToggleConsole,
      deckVisualPreset,
      waveformScale: deckControls.waveformScale,
      safeRuntime: SAFE_MONITOR_RUNTIME,
    }),
  );

  return buildSimpleMonitorDeckHookState({
    activeTrack,
    previewTrackId,
    toggleTrackPreview,
    deckPresetLabel,
    streamAdapterLabel,
    isMonitorActive,
    liveLines,
    selectedAnomalyId,
    simulateLog,
    terminalLinesRef,
    onTerminalScroll,
    registerLineRef,
    focusAnomaly,
    deckBpm,
    trackElapsedSeconds,
    deckDurationSeconds,
    overviewCanvasRef,
    waveformCanvasRef,
    waveformStageRef,
    anomalyBurstRegions,
    selectedBurstRegion,
    overviewAnomalyMarkers,
    overviewWindowLeftPercent,
    overviewWindowWidthPercent,
    overviewPlayheadLeftPercent,
    handleOverviewPointerDown,
    handleOverviewClick,
    handleOverviewAnomalyClick,
    handleOverviewAnomalyPointerDown,
    selectedDeckMarker,
    deckTimelineMarkers,
    deckBeatMarkers,
    handleStagePointerDown,
    handleStageClick,
    waveformScale: deckControls.waveformScale,
  });
}
