import type { SessionScreenPanelsProps } from "./sessionScreenPanelsTypes";

export type SessionScreenPanelsVisualState = Pick<
  SessionScreenPanelsProps,
  | "tracks"
  | "playlists"
  | "sessions"
  | "loading"
  | "mutating"
  | "selectedSessionId"
  | "activeSessionId"
  | "activeSessionMode"
  | "mode"
  | "baseMode"
  | "selectedTemplateId"
  | "selectedSourceId"
  | "selectedTrackId"
  | "selectedPlaylistId"
  | "selectedSource"
  | "selectedTrack"
  | "selectedPlaylist"
  | "selectedBaseLabel"
  | "selectedBaseDetail"
  | "sessionLabel"
  | "sessionLabelPlaceholder"
  | "creating"
  | "sourceOptions"
  | "selectedSession"
  | "selectedSessionBookmarks"
  | "selectedSessionReplayFeedbackRecommendation"
  | "sessionBookmarksBySessionId"
  | "bookmarkContexts"
  | "liveWindowCount"
  | "liveProcessedLines"
  | "liveTotalAnomalies"
>;
