import { useT } from "../../i18n/I18nContext";
import { useMonitor } from "../monitor/MonitorContext";
import {
  buildSessionScreenControllerHookResult,
  buildSessionScreenControllerMonitorSnapshot,
} from "./sessionScreenControllerHookRuntime";
import { buildSessionScreenControllerState } from "./sessionScreenControllerRuntime";
import type { SessionScreenControllerInput } from "./sessionScreenControllerTypes";
import { useSessionScreenLocalState } from "./useSessionScreenLocalState";
import { useSessionScreenControllerSlices } from "./useSessionScreenControllerSlices";

export function useSessionScreenController(input: SessionScreenControllerInput) {
  const t = useT();
  const monitor = useMonitor();
  const monitorSnapshot = buildSessionScreenControllerMonitorSnapshot({
    session: monitor.session,
    metrics: monitor.metrics,
    subscribe: monitor.subscribe,
    isPlaybackPaused: monitor.isPlaybackPaused,
    playbackEventIndex: monitor.playbackEventIndex,
    playbackEventCount: monitor.playbackEventCount,
  });
  const {
    mode,
    setMode,
    baseMode,
    setBaseMode,
    selectedSourceId,
    setSelectedSourceId,
    selectedTrackId,
    setSelectedTrackId,
    selectedPlaylistId,
    setSelectedPlaylistId,
    sessionLabel,
    setSessionLabel,
    creating,
    setCreating,
    createError,
    setCreateError,
    latestUpdate,
    setLatestUpdate,
    directPath,
    setDirectPath,
    isDirectLoading,
    setIsDirectLoading,
    selectedTemplateId,
    setSelectedTemplateId,
    selectedSessionEvents,
    setSelectedSessionEvents,
    boothBedAudioRef,
  } = useSessionScreenLocalState({
    trackCount: input.tracks.length,
  });

  const {
    actions: {
      handleCreateSession,
      handleDirectLaunch,
      handleResumeSession,
      handlePlaybackSession,
      handleReplayBookmark,
    },
    derivedState,
    selectedSessionReplayFeedbackRecommendation,
    booth,
  } = useSessionScreenControllerSlices({
    t,
    input,
    monitorSnapshot,
    localState: {
      mode,
      setMode,
      baseMode,
      setBaseMode,
      selectedSourceId,
      setSelectedSourceId,
      selectedTrackId,
      setSelectedTrackId,
      selectedPlaylistId,
      setSelectedPlaylistId,
      sessionLabel,
      setSessionLabel,
      creating,
      setCreating,
      createError,
      setCreateError,
      latestUpdate,
      setLatestUpdate,
      directPath,
      setDirectPath,
      isDirectLoading,
      setIsDirectLoading,
      selectedTemplateId,
      setSelectedTemplateId,
      selectedSessionEvents,
      setSelectedSessionEvents,
      boothBedAudioRef,
    },
  });
  const {
    sourceOptions,
    selectedSource,
    selectedTrack,
    selectedPlaylist,
    selectedBaseDetails,
    activeSession,
    selectedSession,
    playbackActive,
    liveMonitorActive,
    selectedSessionBookmarks,
    bookmarkContexts,
    sessionLabelPlaceholder,
    readyToRun,
  } = derivedState;

  return buildSessionScreenControllerHookResult(
    buildSessionScreenControllerState({
      t,
      monitor,
      mode,
      setMode,
      baseMode,
      setBaseMode,
      selectedSourceId,
      setSelectedSourceId,
      selectedTrackId,
      setSelectedTrackId,
      selectedPlaylistId,
      setSelectedPlaylistId,
      sessionLabel,
      setSessionLabel,
      creating,
      createError,
      latestUpdate,
      directPath,
      setDirectPath,
      isDirectLoading,
      selectedTemplateId,
      setSelectedTemplateId,
      sourceOptions,
      selectedSource,
      selectedTrack,
      selectedPlaylist,
      selectedBaseDetails,
      handleCreateSession,
      handleDirectLaunch,
      handleResumeSession,
      handlePlaybackSession,
      handleReplayBookmark,
      activeSession,
      selectedSession,
      playbackActive,
      liveMonitorActive,
      selectedSessionBookmarks,
      bookmarkContexts,
      selectedSessionReplayFeedbackRecommendation,
      sessionLabelPlaceholder,
      readyToRun,
      booth,
    }),
  );
}
